beers-book/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  root to: 'posts#index'
  resources :users do
    resources :posts
  end

  resources :posts do
    member do
      post "like", to: "posts#upvote"
      post "dislike", to: "posts#downvote"
    end
  end

  resources :user_friendships

end

beers-book/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

  default_scope -> {order(created_at: :desc)}
  
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, allow_blank: false

end

beers-book/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :all_posts, only: [:index, :create, :update, :destroy]
	respond_to :html, :js
	skip_before_action :verify_authenticity_token

	def upvote
		@post = Post.find(params[:id])
		if current_user.id != @post.user_id
			unless @post.liked_by(current_user)
				@post.upvote_by(current_user)
			end
		end
	end

	def downvote
		@post = Post.find(params[:id])
		if current_user.id != @post.user_id
			unless @post.disliked_by(current_user)
				@post.upvote_by(current_user)
			end
		end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		@post.user = current_user if current_user
		@post.save
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
	end

	private

	def post_params
		params.require(:post).permit(:content, :picture, :user_id)
	end

	def all_posts
	    @posts = Post.all
	end
end

beers-book/app/helpers/posts_helper.rb
module PostsHelper
end

beers-book/app/views/posts/_form.html.erb
<%= simple_form_for @post, remote: true, html: { multipart: true } do |f|   %>
  <%= f.input :content, placeholder: "What's on your mind?", input_html: {class: 'form-control'}, label: false %><br>
  <%= f.input :picture, as: :file, label: 'Add a picture (optional)' %>
  <%= f.button :submit, class: 'btn btn-success pull-right' %>
<% end %> 

beers-book/app/views/posts/_post.html.erb
<% @posts.each do |post| %>
	<div class="row post-boxes" id="post_<%= post.id %>">
		<!-- Shows arrow in top right corner of post if it is that user's post -->
		<% if current_user.id == post.user_id %>
			<div class="post-corner post-box-arrow">
				<div class="btn-group">
				  <button class="btn btn-default btn-sm dropdown-toggle" type="button" style="background-color:#FFFFF0;border:none;" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu pull-right" style="background-color:#FFFFF0;" role="menu">
				    <li class="pull-left"><%= link_to "Edit Post", edit_post_path(post), remote: true %></li>
				    <li class="pull-left"><%= link_to "Delete Post", post, method: :delete, remote: true %></li>
				  </ul>
				</div>
			</div>
		<% end %>
		<!-- post content -->
		<div class="name-grav col-sm-3">
			<%= gravatar_in_post(post.user.email) %>
			<p>
				<%= link_to user_path(post.user) do %>
					<%= post.user.first_name.titleize %> <%= post.user.last_name.titleize %>
				<% end %>
			</p>
			<div class="time-ago">
				<span><%= time_ago_in_words(post.created_at) %> ago</span>
			</div>
			<div class="likes-container">
				<ul>
					<li>
						<%= link_to image_tag("thumbs_up.jpg"), like_post_path(post), method: :post, remote: true %>
					</li>
					<li class="green-bold" id="post_upscore_<%= post.id %>">
						<%= post.get_likes.size %>
					</li>
					<li>
						<%= link_to image_tag("thumbs-down.jpg"),dislike_post_path(post), method: :post, remote: true %>
					</li>

					<li class="red-bold" id="post_downscore_<%= post.id %>">
						<%= post.get_dislikes.size %>
					</li>
						
				</ul>
			</div>
		</div>
		<div class="post-content col-sm-8">
			<p id="post-content-<%= post.id %>"><%= post.content %></p>
			<%= image_tag post.picture.url if post.picture? %>
			<div class="col-md-10 col-md-offset-1 edit-form-<%= post.id %>" style="display:none;"></div>
			<p class="text-center">
				<%= link_to "Add Comment", new_post_comment_path(post), remote: true %>
			</p>
			<div class="col-md-10 col-md-offset-1" id="comment-form" style="display:none;"></div>
		</div>
	</div>
<% end %>

beers-book/app/views/posts/create.js.erb
$('.all-posts').html(' <%= j (render @post) %> ');
$('#post-modal').modal('hide');

beers-book/app/views/posts/destroy.js.erb
$('#post_<%= @post.id %>').fadeOut("slow");

beers-book/app/views/posts/downvote.js.erb
var postScore = $('#post_downscore_<%= @post.id %>');
postScore.text(<%= @post.get_dislikes.size %>);

beers-book/app/views/posts/edit.js.erb
$('#post-content-<%= @post.id %>').fadeOut("fast"); 
$('#post-content-<%= @post.id %>').parent().find('img').addClass('hide');
$('.edit-form-<%= @post.id %>').html("<%= j (render 'form') %>");
$('.edit-form-<%= @post.id %>').fadeIn("fast");

beers-book/app/views/posts/index.html.erb
<% if user_signed_in? %>
	<div class="row">
		<div class="col-md-2 col-md-offset-4">
			<%= link_to new_post_path, remote: true do %>
	      		<button class="btn btn-default">+New Post</button>
	    	<% end %>
	  </div>
	</div>

	<div class="row">
	  <div class="col-md-6 col-md-offset-2" id="post-form" style="display:none;"></div>
	</div>

	<div class="row">
	    <div class="col-md-7 col-md-offset-2 all-posts">
			<%= render @posts %>
	    </div>
	</div>
<% end %>

beers-book/app/views/posts/new.js.erb
$('#post-modal').find('.modal-body').html("<%= j (render 'form') %>");
$('#post-modal').modal('show');

beers-book/app/views/posts/update.js.erb
$('.all-posts').html(' <%= j (render @post) %> ');
$('.edit-form-<%= @post.id %>').slideUp(350); 

beers-book/app/views/posts/upvote.js.erb
var postScore = $('#post_upscore_<%= @post.id %>');
postScore.text(<%= @post.get_likes.size %>);