beers-book/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  root to: 'posts#index'
  resources :users do
    resources :posts
  end

  resources :posts do
    member do
      post "like", to: "posts#upvote"
      post "dislike", to: "posts#downvote"
    end
  end

  resources :user_friendships

end

beers-book/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save { self.email = email.downcase }

  validates :first_name, presence: true, allow_blank: false
  validates :last_name, presence: true, allow_blank: false
  validates :user_name, presence: true, uniqueness: true, allow_blank: false
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, length: {minimum: 8}

  has_many :posts, dependent: :destroy
  has_many :user_friendships
  has_many :friends, -> {where(user_friendships: {state: 'accepted'})}, through: :user_friendships
  has_many :pending_user_friendships, -> {where(state: 'pending')}, class_name: 'UserFriendship', foreign_key: :user_id 
  has_many :pending_friends, through: :pending_user_friendships, source: :friend

end

beers-book/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

beers-book/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

beers-book/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

beers-book/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   @user = User.new
  #   respond_to do |format|
  #     format.html
  #     format.js
  #   end
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) do |u|
          u.permit(:first_name, :last_name, :user_name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
        end
    end
    
    def configure_account_update_params
        devise_parameter_sanitizer.for(:account_update)do |u|
          u.permit(:first_name, :last_name, :user_name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache)
      end
    end
  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

beers-book/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

beers-book/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

beers-book/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end
end

beers-book/app/helpers/users_helper.rb
module UsersHelper
end

beers-book/app/views/users/show.html.erb
<div class="col-sm-5" id="friends">
	<div class="row">
		<div class="col-sm-12 add-friend">
			<%= link_to new_user_friendship_path(friend_id: @user) do %>
				<button class="btn btn-primary">Add <%= @user.first_name.titleize %> <%= @user.last_name.titleize %> as a friend</button>
			<% end %>
		</div>
		<div class="friends-box col-sm-12">
			<div class="friends-title">
				<p>Friends</p>
			</div>
			<div class="friend-content">
				<%= render 'user_friendships/index' %>
			</div>
		</div>
	</div>
</div>

<div class="col-sm-7 all-posts" id="user-posts">
	<% @posts.each do |post| %>
	<div class="row col-sm-12 post-boxes" id="post_<%= post.id %>">
		<!-- Shows arrow in top right corner of post if it is that user's post -->
		<% if current_user.id == post.user_id %>
			<div class="post-corner post-box-arrow">
				<div class="btn-group">
				  <button class="btn btn-default btn-sm dropdown-toggle" type="button" style="background-color:#FFFFF0;border:none;" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu pull-right" style="background-color:#FFFFF0;" role="menu">
				    <li class="pull-left"><%= link_to "Edit Post", edit_post_path(post), remote: true %></li>
				    <li class="pull-left"><%= link_to "Delete Post", post, method: :delete, remote: true %></li>
				  </ul>
				</div>
			</div>
		<% end %>
		<!-- post content -->
		<div class="name-grav col-sm-3">
			<%= gravatar_in_post(post.user.email) %>
			<p>
				<%= link_to user_path(post.user) do %>
					<%= post.user.first_name.titleize %> <%= post.user.last_name.titleize %>
				<% end %>
			</p>
			<div class="time-ago">
				<span><%= time_ago_in_words(post.created_at) %> ago</span>
			</div>
			<div class="likes-container">
				<ul>
					<li>
						<%= link_to image_tag("thumbs_up.jpg"), like_post_path(post), method: :post, remote: true %>
					</li>
					<li class="green-bold" id="post_upscore_<%= post.id %>"><%= post.get_likes.size %></li>
					<li>
						<%= link_to image_tag("thumbs-down.jpg"),dislike_post_path(post), method: :post, remote: true %>
					</li>

					<li class="red-bold" id="post_downscore_<%= post.id %>"><%= post.get_dislikes.size %></li>
						
				</ul>
			</div>
		</div>
		<div class="post-content col-sm-8">
			<p id="post-content-<%= post.id %>"><%= post.content %></p>
			<%= image_tag post.picture.url if post.picture? %>
			<div class="col-md-6 col-md-offset-2 edit-form-<%= post.id %>" style="display:none;"></div>
		</div>
	</div>
<% end %>
</div>