beers-book/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  root to: 'posts#index'
  resources :users do
    resources :posts
  end

  resources :posts do
    member do
      post "like", to: "posts#upvote"
      post "dislike", to: "posts#downvote"
    end
  end

  resources :user_friendships

end

beers-book/app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

	attr_accessible :user, :friend, :user_id, :friend_id, :state

	state_machine :state, initial: :pending do
		after_transition on: :accept, do: :send_acceptance_email

		state :requested

		event :accept do
			transition any => :accepted
		end
	end

	def self.request(user1,user2)
		transaction do
			friendship1 = create!(user: user1, friend: user2, state: 'pending')
			friendship2 = create!(user: user2, friend: user1, state: 'requested')

			friendship1.send_request_email
			friendship1
		end
	end

	def send_request_email
		UserNotifier.friend_requested(id).deliver
	end	

	def send_acceptance_email
		UserNotifier.friend_request_accepted(id).deliver
	end
end

beers-book/app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@user_friendships = current_user.user_friendships.all
	end
	
	def new
		if params[:friend_id]
			@friend = User.find(params[:friend_id])
			@user_friendship = current_user.user_friendships.new(friend: @friend)
		else
			flash[:error] = "Friend required"
		end
	rescue ActiveRecord::RecordNotFound
		render file: 'public/404', status: :not_found
	end

	def create
		if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
			@friend = User.find(params[:user_friendship][:friend_id])
			@user_friendship = current_user.user_friendships.new(friend: @friend)
			@user_friendship.save
			flash[:success] = "You are now friends with #{@friend.first_name.titleize}!"
			redirect_to user_path(@friend)
		else
			flash[:error] = "Friend required"
			@user_friendship = current_user.user_friendships.new(friend: @friend)
		end
	end
end

beers-book/app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

beers-book/app/views/user_friendships/_index.html.erb
<% if @user_friendships %>
	<% @user_friendships.each do |friendship| %>
		<% friend = friendship.friend %>
		<div class="friend row" id="<%= dom_id(friendship) %>">
			<div class="col-sm-1">
				<%= link_to image_tage(gravatar_for(friend)), user_path(friend) %>
			</div>
			<div class="col-sm-7">
				<strong><%= friend.first_name.titleize %> <%= friend.last_name.titleize %></strong><br>
				<% if friendship.pending? %>
					<em>Friendship is pending.</em> <%= link_to "Delete", edit_user_friendship_path(friendship)  %>
				<% end %>
				<% if friendship.requested? %>
					 	<em>Friendship requested.</em> <%= link_to "Accept", edit_user_friendship_path(friendship) %>
				<% end %> 
				<% if friendship.accepted? %>
					<em>Friendship accepted <%= friendship.updated_at %>.</em> <%= link_to "Update friendship", edit_user_friendship_path(friendship)  %>
				<% end %>
			</div>
		</div>
	<% end %>
<% else %>
	<p>You currently have no friends.</p>
<% end %>

beers-book/app/views/user_friendships/new.html.erb
<% if @friend %>
	<h1><%= @friend.first_name.titleize %> <%= @friend.last_name.titleize %></h1>
	<p>Do you really want to friend <%= @friend.first_name.titleize %> <%= @friend.last_name.titleize %>?</p>

	<%= form_for @user_friendship, method: :post do |f| %>
		<div class="form form-actions">
			<%= f.hidden_field :friend_id, value: @friend.id %>
			<%= submit_tag "Yes, Add Friend", class: 'btn btn-primary' %>
			<%= link_to "Cancel", user_path(@friend), class: 'btn btn-danger'  %>
		</div>
	<% end %>
<% end %>